### ISSUE TITLE
Login problem!

### ISSUE THREAD

**Issue by nishantmendiratta** [aheckmann/muri#6]
Firstly i want to thank you all for creating such a useful lib. But, i came across the following issue.
As there is a function defined which splits the 'uri' in parts, it's not working as per the expectations.

Here is the case of connection string which leads to an error, even if the 'uri' provided by user is correct.

`var connectionString = 'mongodb://user2:password@124@dbhost.com:port/'+dbName;` 

Following are the expected parts
    `auth = 'user2:password@124'`
    `uri = 'dbhost.com:port/'+dbName;'`

But as per current code 'uri' is divided using following LOC
   `uri.split(/@/);`
Which leads to 
    `auth = 'user2:password'`
    `uri = '124dbhost.com:port/'+dbName;'`

So there may be chances that 'user_name' and 'user_password' may contain '@' symbol and this case is not handled in library and it could lead to a dissatisfied user, Who is passing all the requested params correctly but still gets following error.

 `{ name: 'MongoError', message: 'getaddrinfo ENOTFOUND' }`

**Comment by vkarpov15** [comment]
Actually, the correct behavior is for muri to throw an exception in this case. For one,'@' is a reserved character in the [URI spec](http://tools.ietf.org/html/rfc3986#section-2.2). There's also internal reasons for this behavior. The correct way is to do `encodeURIComponent()` on both username and password.

**Comment by CallMeLaNN** [comment]
Muri should expect the `user` and the `password` part of the URI is encoded. So when ever it try to parse, it should decode the `user` and `password` using decodeURIComponent. I will log another issue related to this.

**Comment by vkarpov15** [comment]
Fixed by #11
